apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
    - name: argocd-image-updater
      repo: https://argoproj.github.io/argo-helm
      version: 0.12.0
      releaseName: argocd-image-updater
      valuesFile: ../values-argocd-image-updater.yaml
