apiVersion: v1
data:
  BOOKING_SERVICE_URL: http://ticketing-main-service:8080
  PERFORMANCE_SERVICE_URL: http://ticketing-main-service:8080
  QUEUE_SERVICE_URL: http://ticketing-queue-service:8080
  S3_SERVICE_URL: http://ticketing-main-service:8080
  SEAT_SERVICE_URL: http://ticketing-main-service:8080
  SERVER_PORT: "8080"
  SPRING_PROFILES_ACTIVE: local
  USER_SERVICE_URL: http://ticketing-main-service:8080
kind: ConfigMap
metadata:
  name: ticket-admin-config
