apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: test-endpoint
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: backend-need-endpoint
    creationPolicy: Owner
  data:
  - secretKey: DB_URL
    remoteRef:
      key: test/ticket/endpoint
      property: DB_URL
  - secretKey: REDIS_HOST
    remoteRef:
      key: test/ticket/endpoint
      property: REDIS_HOST
  
