# alb-to-nginx-ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: alb-to-nginx
  namespace: ingress-nginx
  annotations:
    # AWS Load Balancer Controller 사용
    kubernetes.io/ingress.class: alb
    
    # ALB 기본 설정
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: instance  # NGINX NodePort로 전달
    
    # HTTPS 설정
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-northeast-2:911723818289:certificate/e5e4be1d-992c-45a7-853c-fe5ea9d42e08 
    
    # Health Check (NGINX Ingress Controller)
    alb.ingress.kubernetes.io/healthcheck-path: /healthz
    alb.ingress.kubernetes.io/healthcheck-port: "30080"
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: "15"
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: "5"
    alb.ingress.kubernetes.io/healthy-threshold-count: "2"
    alb.ingress.kubernetes.io/unhealthy-threshold-count: "2"
    
    # Security Groups
    alb.ingress.kubernetes.io/security-groups: sg-0d3173e2534c22986
    
    # Tags
    alb.ingress.kubernetes.io/tags: Environment=dev,Project=ticket,Owner=pjy,Team=kubespray
    # ALB 이름
    alb.ingress.kubernetes.io/load-balancer-name: kbsp-api-alb
    
    # IP Address Type
    alb.ingress.kubernetes.io/ip-address-type: ipv4
    
    external-dns.alpha.kubernetes.io/hostname: api.kbsp.ddcn41.com

spec:
  ingressClassName: alb
  rules:
  - host: api.kbsp.ddcn41.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ingress-nginx-controller
            port:
              number: 80  # NGINX의 Service Port (NodePort 30080으로 매핑됨)
